import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Task 01</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full min-h-screen bg-slate-800 px-20 py-8 flex flex-col gap-4">
        <div className="text-white text-xl font-bold">Нэмэлт оноо</div>
        <img
          alt="task1"
          src="/images/more.png"
          className="w-full object-contain border border-white"
        />
      </div>
    </>
  );
}
