import Contact from "@/components/contact";
import Header from "@/components/header";
import Home from "@/components/home";
import Project from "@/components/project";
import Head from "next/head";
import Image from "next/image";

export default function Index() {
  return (
    <>
      <Head>
        <title>Component tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header  */}
      <Header />

      {/* container */}
      <div className="px-40 ">
        {/* home */}
        <Home />
        {/* project */}
        <Project />
        {/* contact */}
        <Contact />
      </div>
    </>
  );
}
