import GameBoard from "@/components/gameBoard";
import SelectHero from "@/components/selectHero";
import Head from "next/head";

export default function Index() {
  return (
    <>
      <Head>
        <title>Component tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full min-h-screen bg-slate-900 py-20 px-40">
        <div className="text-3xl text-white font-bold text-center">
          Cute fight
        </div>
        <GameBoard>
          <SelectHero />
        </GameBoard>
      </div>
    </>
  );
}
