import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Task 01</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen bg-slate-800">
        <div className=" w-48 h-48 bg-red-600 ">
          <div className="w-20 h-20 bg-white rounded-full "></div>
        </div>
      </div>
    </>
  );
}
